### ISSUE TITLE
Bug in LWP::UserAgent::JSON->rebless_maybe

### ISSUE THREAD

**Issue by g0ga** [skington/lwp-json-tiny#2]
Due to HTTP::Message delegating methods to HTTP::Headers using AUTOLOAD and creating those in runtime LWP::UserAgent::JSON->rebless_maybe is not going to work even when content-type is  application/json since there is no such method and "if" statement going to fail on https://github.com/skington/lwp-json-tiny/blob/master/lib/LWP/UserAgent/JSON.pm#L146

**Comment by skington** [comment]
Fixed in 0.012 - thank!
